### ISSUE TITLE
Terrible performance while typing

### ISSUE THREAD

**Issue by corneil** [esteinberg/plantuml4idea#125]
Typing just has no effect for 2-3 seconds at a time.
I would expect the plugin to wait for save or a certain amount of time of no typing before updating the diagram.

**Comment by krasa** [comment]
I have no idea what are you trying to say.

**Comment by corneil** [comment]
As I type the text for a plantuml diagram sometimes the keystrokes are not
accepted for 2-3 seconds. It is not asif they keystrokes are buffered. The
keystrokes are just ignored.
It is work for the text after a : as in [Component[ --> myinterface : uses


I would expect the plugin to wait for a period of me not typing before
updating the diagram or until a save the file.



[image: --]
Corneil du Plessis
[image: https://]about.me/corneil
<https://about.me/corneil?promo=email_sig>

**Comment by krasa** [comment]
"eystrokes are not accepted for 2-3 seconds." 
What does that mean? Do they not appear in the editor?

"I would expect the plugin to wait for a period of me not typing before
updating the diagram "
that is exactly what is happening, go to setting to increase the  delay time.

**Comment by fktpp** [comment]
I got this issue too. the IDEA will be very slow to user input event when plantuml graph is big enough. I switch to eclipse plantuml plugin to aovid this issue. It seemed that eclipse plugin have this issue too, but the slowness is just a little bit better than IDEA one.

The user experience feels like the IDE was **hang** and **not response to user input** for a while, until graph preview was updated.

**Comment by krasa** [comment]
That's strange, because the rendering is done in background. What CPU do you have? 
Does it hang when you increase the delay, so that it is not rendering anything?

Do you have some threaddumps in location like this? `.IntelliJIdea16\system\log\threadDumps-20160613-215318-IU-162.844.8\freeze-20160615-025052-2`

If not, you could add this to `<installation>/idea.properties`, to have them for GUI freezes longer than 1 second:
```
performance.watcher.interval=1
performance.watcher.threshold=1
```

Or CPU sample by VisualVM would help. It could be also OS related.

**Comment by krasa** [comment]
So I tried Eclipse, and it totally hangs because it does not render on background. But it also does not check syntax errors or highlights syntax or automatically render.

You can disable syntax check in settings - it is done in background, same as rendering, but that's together with GUI thread, in total 3 threads working parallely, so if you have only 2 cores it might cause trouble, 
I will add a nice way to disable automatic rendering, so you can press a shortcut to render.

**Comment by krasa** [comment]
You can try it now https://github.com/esteinberg/plantuml4idea/releases/tag/2.2.0

**Comment by fktpp** [comment]
Hello there, it feels the issue was fixed. I am not sure, but I can't reproduce it on IDEA2016.1 with plantuml4idea 2.2. 

I've just reinstalled IDEA, this time it (the installer) provide me a choice to create 64bit launcher. Not sure if this makes difference.

I'am running 64bit launcher launched IDEA with plantuml4idea 2.2 very happy.

Thanks for the great plugin!!

**Comment by krasa** [comment]
Maybe you just didn't have enough heap, and the hang was full GC?
