### ISSUE TITLE
Add a build script!

### ISSUE THREAD

**Issue by aadrian** [esteinberg/plantuml4idea#152]
Please add build script to the plug-in, e.g. Gradle is a natural choice:
http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html

since it makes everything much easier.

Thank you.

**Comment by krasa** [comment]
The current system seems to me pretty simple and easy.
![plantuml](https://cloud.githubusercontent.com/assets/1160875/24718610/f66fd85a-1a36-11e7-8180-59100603a740.gif)

**Comment by aadrian** [comment]
> The current system seems to me pretty simple and easy.

Sorry but that's not really professional  :) :
 - it can't be done by a CI (e.g. Travis for free)
 - no tests can be run automatically (but the CI too for free)
 - builds are not reproducible, since depend on the IDE settings (and import).

The link I provided, is there recommended way by Jetbrains too, does all of the above, and also does not exclude manual debugging either, since IntelliJ will use that file to build/sync it's project.

Thank you.

**Comment by krasa** [comment]
Not even JetBrains uses it except for a few of plugins.
This plugin is many years older than the "recommended" way and there was never a need for migrating. 

If you pull request it, then I will try it any maybe merge it.

**Comment by aadrian** [comment]
> This plugin is many years older than the "recommended"

Not true. It's quite actual: https://github.com/JetBrains/gradle-intellij-plugin and many use it, and it simplifies the work allot, but also the contributions of others to your project.

> If you pull request it, then I will try it any maybe merge it.

Here https://github.com/esteinberg/plantuml4idea/pull/158 is the most minimal PR that works for building and running. As I described there, it could be further improved.

**Comment by alwyn** [comment]
Let me see.  You want to be able to automate the build.  

Which to me means that you have much such significant changes that the normal plugin update process doesn't work.

How about you create the gradle script, contribute it and any changes you feel like?

**Comment by aadrian** [comment]
> How about you create the gradle script, contribute it and any changes you feel like?

@alwyn I already done that almost a year ago and contributed the PR https://github.com/esteinberg/plantuml4idea/pull/158 but it was not merged to this day :)

**Comment by krasa** [comment]
Imho it is not clear whether the gradle build actually helps more than it hurts, disregarding those long hours to make it actually somehow nice.

First opening of a gradle project takes me 7 minutes
- 6:30 to download gradle, dependencies and sources
- another 30s to index it

Check it for yourself: https://github.com/esteinberg/plantuml4idea/tree/gradle


Opening and manually setting and debugging the project manually takes under 45s.

The good thing about gradle:
- releasing  (but you have to fuck with `login.properties` and run  `git update-index --assume-unchanged login.properties` which hides it from the change list, but you might have to unhide it if someone changes it...
Then you have to check on the web if it was actually done right. Compared to like 15s to build and upload it manually, not much better.)
- handling of different IJ versions with source downloading - I personally do not even like that, since the repo is painfully slow so installing IJ manually could be even faster - and you already have the one you are running anyway. I have all old versions I need downloaded and installed already, and having sources is not that important anyway because of decompiling. Also, you need to have `intellij-community` anyway for problem-solving.


Then there are annoying things like:
- stopping `runIdea` task - it takes forever before it closes the IDE
- bunch of additional files
- future maintenance

**Comment by krasa** [comment]
I've tried Gradle again and it is just terrible. 
- hotswap of one class takes 15s instead of 2s - it reloads everything because of instrumentation `https://github.com/JetBrains/gradle-intellij-plugin/issues/459`
- start of the IDE 10s to see a splashcreen compared to 2s without it.

Closing this until the performance is fixed.
