### ISSUE TITLE
[Markdown] PlantUML blocks in Markdown previews

### ISSUE THREAD

**Issue by dkarlovi** [esteinberg/plantuml4idea#161]
[Gitlab supports having PlantUML blocks in Markdown](https://docs.gitlab.com/ee/administration/integration/plantuml.html#creating-diagrams). It would be a nice feature to allow rendering the blocks in Markdown previews.

Thanks.

**Comment by aadrian** [comment]
I think this feature request should than go to the IntelliJ markdown plug-in.

**Comment by dkarlovi** [comment]
I see, so they'd check if a PlantUML rendering service (or something, not a plugin-person) is available and then use it to render parts of it?

**Comment by aadrian** [comment]
> so they'd check if a PlantUML rendering service (or something, not a plugin-person) is available and then use it to render parts of it?

Yeah, something like that :). This is not the only way to integrate it however, since there also exists:
 - https://github.com/plantuml/plantuml-server (that you can host yourself, or the Markedown plug-in could start it)
 - http://www.plantuml.com/plantuml/ - the server from above hosted by PlantUML team itself - many tools simply talk to this "free" service
 - include the plantuml jar in the markdown plug-in too, in order to avoid "plug-in dependencies"

Also, unfortunately there are more active active and competing Markdown plug-ins:
 - one from Jetbrains: https://plugins.jetbrains.com/plugin/7793-markdown-support -  I suppose this is what most users have, so here should be this feature requested.
 - https://plugins.jetbrains.com/plugin/7896-markdown-navigator
 - https://plugins.jetbrains.com/plugin/7701-gfm
 - https://plugins.jetbrains.com/plugin/7391-asciidoc
 - etc.

**Comment by dkarlovi** [comment]
I'll open a feature suggestion for the first one, linking here. Thanks for your help!

**Comment by dkarlovi** [comment]
Done at https://youtrack.jetbrains.com/issue/RUBY-19041 with only slight delay, in terms of how old the Universe is. :)
