### ISSUE TITLE
Puml file editor

### ISSUE THREAD

**Issue by linux-china** [esteinberg/plantuml4idea#17]
Any plan to implement puml file editor, such as code completion, syntax high light and inspection?

**Comment by AdrieanKhisbe** [comment]
Hey All!
@Stefku, did you drop your idea, I checked your project intellij-plantuml-syntaxcheck and saw no jflex.

@esteinberg I am currently working on the org4idea plugin contributing to it's editing and syntax highlighting features. Since I'm also an user of your plantuml plugin, I thought I could put the knowledge developed to improved your plugin and bring basic editing ans syntax features .

Tell me what you think, 

Best regards :)

**Comment by Stefku** [comment]
Hi @AdrieanKhisbe,
I tried hard to create a syntax for pump. But probably I'm too inexperienced in creating grammars because for me it seems that puml syntax has a lot of possibilities to create same building blocks like definitions that a grammar like I tried is not able to cover. Any ideas?
Bye,
Stefan

**Comment by AdrieanKhisbe** [comment]
Hey @Stefku , 
indeed puml syntax doesn't seems that easy, However there is no need to have a perfect grammar to offer some feature as basic syntax highlighting (like kerword), etc. 

However to do a proper grammar, might be better to use the idea Grammar-Kit enabling to write bnf grammar and generating the psi ast for you.

So far I forked the project, and waiting to have @esteinberg green light to begin.

Adrien

**Comment by 6zow** [comment]
I'm working on the grammar. So far completed sequence and component diagrams, still working on class diagrams. Will make it available within 2 weeks, most likely just with syntax highlighting and cryptic error reporting, maybe with some basic intents. After that you're welcome to join me and add support for other diagram types, as well as improved error messages and some advanced actions (e.g. I started working on code completion and references in class diagrams on a now abandoned codebase, may port it).

**Comment by Stefku** [comment]
Hi @AdrieanKhisbe, I used the Grammar-Kit. Well, I tried, though. So, I'm looking forward to see the solution of @6zow.

**Comment by AdrieanKhisbe** [comment]
@Stefku, my bad I thought you only used flex (that's like that so far on org4idea, with no real parsing).
Also looking forward for your grammar and editor  @6zow :)
Good luck!

**Comment by esteinberg** [comment]
Looks like everybody is waiting for @6zow pull request :)

**Comment by AdrieanKhisbe** [comment]
Hey @6zow,
where are you with the grammar and editor? :)

**Comment by krasa** [comment]
@6zow any news?

**Comment by 6zow** [comment]
I'm sorry, I was distracted from this activity for too long. Let me try to
finish it by the end of this week.
If anyone has any experience with running Grammar Kit and JFlex as
standalone tools, please let me know. I had some issues with generating
compilable code in a script.

**Comment by AdrieanKhisbe** [comment]
I was facing the same issue for org4idea, but didn't really had time to dig in.

Here is some linked I bookmarked:

Plugin with gradle build: https://github.com/Vektah/idea-rust/blob/master/build.gradle

Plugin using grammar kit: https://github.com/carymrobbins/intellij-haskforce
https://github.com/ignatov/intellij-erlang

**Comment by 6zow** [comment]
Andriean,

These links are interesting, thank you! Both projects using Grammar Kit
just check-in generated files. That's something I want to avoid. Another
problem is that when I tried to generate code using standalone approach
(using the same jar files as used when you launch it from IDEA), it
generated some code which did not compile. But that's JFlex, so I'll try to
play with it to see what version and/or parameters generate good code.

Thanks!

**Comment by AdrieanKhisbe** [comment]
For the two project I know, just gave them as reference. 
 (plus in latest idea  a glitch make them generated in src...)
Last time I search I didn't found anyplugin that both was really automated, and used Grammar kit :/

we should ask JetBrains to make a gradle plugin :D

**Comment by 6zow** [comment]
I ended up with a bash script which works, but is not cross-platform. Tried to use gradle, but it takes too much time, since I did not use it before. Any suggestions?

The first batch (sequence, class and component) is ready, will submit soon. There are some minor improvements to follow. Stay tuned.

**Comment by krasa** [comment]
bash is fine, even for windows - imho everyone has Git Bash

**Comment by krasa** [comment]
Simple grammar added, supporting navigation and renaming, keyword are highlighted simply by plaintext matching: https://github.com/esteinberg/plantuml4idea/commit/bd81a9bcf53235ef6ce529f1a6bc75973e8f2c47 

Having a proper grammar seems not feasible.
