### ISSUE TITLE
Hyperlinks don't do anything

### ISSUE THREAD

**Issue by owen9825** [esteinberg/plantuml4idea#252]
I can write hyperlinks fine in my PlantUML diagram and the text renders in blue, with the underline, as though it is a hyperlink, but clicking on it (in the image preview) doesn't actually do anything.

I see that I can copy it as a PlantUML server link (<http://www.plantuml.com/plantuml/uml>), where there's a `diagram` consisting of the `img` and a `map`, which has the hyperlink. Would it please be possible to enable something like that for the IDEA plugin?

Ideally, I'd like to include hyperlinks like `file://../../app/MyClass.java`, but since I need to go to the web to render things, the best I can do is `https://github.com/…/MyClass.java`, which isn't conducive to editing.

**Comment by krasa** [comment]
did you enable it?
![image](https://user-images.githubusercontent.com/1160875/76856610-e44c4780-6853-11ea-9070-c2cb4f8ff2f8.png)

**Comment by owen9825** [comment]
Oh yes I should have mentioned that sorry. I did indeed select that option. I wasn't quite sure how long to wait, but after 20 seconds, the links still weren't interactive.

**Comment by krasa** [comment]
It only slows the rendering, there is no "after".

Post an example.

**Comment by owen9825** [comment]
![sample UML](https://user-images.githubusercontent.com/1582341/76860508-8870c700-6831-11ea-9000-b1356f5c4a41.png)
Here is a minimal example

**Comment by krasa** [comment]
Hmm this no longer works:
https://github.com/esteinberg/plantuml4idea/blob/2b644d0b7a27a5d40d985c9fe1ab327b7dc2dc16/src/org/plantuml/idea/rendering/ImageItem.java#L214-L235
it need to process:
```
        <a href="https://giuthub.com/" target="_top" title="https://giuthub.com/" xlink:actuate="onRequest"
           xlink:href="https://giuthub.com/" xlink:show="new" xlink:title="https://giuthub.com/" xlink:type="simple">
            <text fill="#0000FF" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs"
                  text-decoration="underline" textLength="35" x="182" y="67.1045">github
            </text>
        </a>
```
@koroandr

**Comment by arvidj01** [comment]
I will the following scenario ...

IntelliJ 2020.1 running on Mac OS

Created and ER diagram within a .adoc using the AsciiDoc plugin. Included this in an .adoc file ...

```
[[data-repository-er-diagram]]
.Data Repository ER Diagram
[plantuml%interactive, data-repository-er-diagram, svg, alt="Data Repository ER diagram", align="center"]
----
entity ... {
  *id: string
  [[#accessLevel{Access Level} Access Level Details]]
}
...
----
```

.svg file is generated and active links are generated. Note that the '%interactive' attribute was the key to getting the links to generate correctly. Otherwise they simply LOOKED like links, blue and underlined, but did not activate the cursor change when rolled over nor were they sensitive to a click.

I then moved the code between the ---- marks over to a .puml file and added the appropriate @startuml and @enduml directives. I then using the PlantUML plugin to generate the image. The image renders correctly but I am stymied by two items.

It is not clear to me now to instruct the plugin to generate a .svg file other than changing the extension on the proposed file name from .png to .svg when saving. This may be the appropriate way to accomplish that task as a .svg file is actually generated, but I was not sure.

The other challenge, and the one relevant to this thread, is that even when I change the extension to .svg the links in the generated file do not work. I am guessing that if there was some way to pass the '%interactive' to the underlying PlantUML things would be fine. I've not been able to find a PlantUML command that will accomplish the same goal as having the option passed directly to PlantUML as part of what I am guessing is part of the command line.

Thoughts?

**Comment by krasa** [comment]
It is not a problem to generate svg with links, the problem is displaying it, I will try to find some component for it. 

Exporting svg works fine, and the resulting xml contains links, e.g. Chrome can handle them.

**Comment by krasa** [comment]
You can try it: https://github.com/esteinberg/plantuml4idea/releases/download/2.24.0/plantuml4idea.zip

(install the whole zip, or drag it into the editor)

**Comment by owen9825** [comment]
> You can try it: https://github.com/esteinberg/plantuml4idea/releases/download/2.24.0/plantuml4idea.zip
> 
> (install the whole zip, or drag it into the editor)

oh thanks, works well :) This is very handy
