### ISSUE TITLE
IDEA context action: reverse arrow(s)

### ISSUE THREAD

**Issue by singalen** [esteinberg/plantuml4idea#81]
Some day, when the plugin supports the syntax, I'd love to have an IDEA context action (the one for Alt-Enter) like "Reverse arrow layout", that turns arrow the other way around:
`[component1] -> [component2]`
to
`[component2] <- [component1]`
I had to do a lot of these by hand when changing a diagram layout.
Maybe this one could be accompanied with "flip horizontal/vertical" action.
Maybe it could perform the action on several arrows, if there were several in current text selection.

**Comment by krasa** [comment]
Maybe I could implement some dumb action even without the PSI...

**Comment by krasa** [comment]
So I've made an Intention which reverses basically anything with '.' or '-' inside it - PlantUml has something like 30 different arrows...

![arrows](https://cloud.githubusercontent.com/assets/1160875/7972373/174ad0ae-0a4c-11e5-8842-a5fb2a4dd6fa.gif)

https://github.com/krasa/plantuml4idea/tree/arrowIntention

Should I merge it and release it? :)

**Comment by esteinberg** [comment]
Looks like a nice feature, lets release it!

**Comment by krasa** [comment]
one thing, for now I hooked it only on PlantUml file type, not sure about performance of org.plantuml.idea.plantuml.PlantUml#extractSource on huge files, since it is executed all the time...
https://github.com/krasa/plantuml4idea/blob/arrowIntention/src/org/plantuml/idea/intentions/ReverseArrowIntention.java#L32-32

**Comment by krasa** [comment]
It was just released.
